name: My Github Workflow
on: [push]
jobs:
  Test-github-actions:
  - runs-on: ubuntu-latest
    steps:
      - run: apt-get install python3
      - run: apt-get install docker
      - run: docker version
      - name: 'Check docker version'
      - run: python -V
      - name: 'Check python version'