name: My Github Workflow

on: [push]

jobs:
  Python-and-Docker-version:

    runs-on: ubuntu-latest

    steps:
       - name: Python version
         run: python -V
       - name: Docker version
         run: docker version

  Test-app-with-PyLint:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - name: install pylint
         run: sudo apt-get install pylint
       - name: install python3
         run: sudo apt-get install python3
       - name: install falsk
         run: pip install Flask
       - name: test app by PyLint
         run: pylint app.py

  Build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2

       - name: Budowanie i uruchamianie kontenera docker
       - uses: docker-practice/actions-setup-docker@master
       - run: |
           sudo docker build --tag test-flask-app:1.0 -t test-flask-app:latest .
           docker run -it -p 5000:5000 --name my-app test-flask-app

      #  - uses: actions/setup-
      #  - name: install docker
      #    run: |
      #       sudo apt-get update
      #       sudo apt install docker

      #  - 
      #    uses: docker/setup-buildx-action@v1
      #    id: buildx
      #    with:
      #      install: true

      #  - 
      #    name: Build
      #    run: docker build .

      #  - uses: actions/setup-
      #  - name: install docker
      #    run: |
      #      sudo apt-get update
      #      sudo apt install docker
      #  - name: Docker build
      #    run: sudo docker build --tag test-flask-app:1.0 -t test-flask-app:latest .
      #  - name: Docker run
      #    run: docker run -it -p 5000:5000 --name my-app test-flask-app
