name: My Github Workflow

on: [push]

jobs:
  Python-and-Docker-version:

    runs-on: ubuntu-latest

    steps:
       - name: Python version
         run: python -V
       - name: Docker version
         run: docker version

  Test-app-with-PyLint:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - name: test app by PyLint
         run: |
           sudo apt-get install pylint
           sudo apt-get install flask
           pylint app.py