name: My Github Workflow
on: [push]
jobs:
  Test-github-actions:
    runs-on: ubuntu-latest
    steps:
      - echo "CI/CD pipeline"
      - run: apt-get install python3
      - run: apt-get install docker
      - run: docker version
        displayname: 'Check docker version'
      - run: python -V
        displayname: 'Check python version'