name: My Github Workflow

on: [push]

jobs:
  Python-and-Docker-version:

    runs-on: ubuntu-latest

    steps:
       - name: Python version
         run: python -V
       - name: Docker version
         run: docker version
       - name: flask and click version
         run: flask --version

  Test-app-with-PyLint:

    runs-on: ubuntu-latest

    steps:
       - name: test app by PyLint
         run: |
           apt-get install pylint
           pylint ../app.py