name: My Github Workflow

on: [push]

jobs:
  Python-and-Docker-version:

    runs-on: ubuntu-latest

    steps:
       - name: Python version
         run: python -V
       - name: Docker version
         run: docker version

  Test-app-with-PyLint:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - name: install pylint
         run: sudo apt-get install pylint
       - name: install python3
         run: sudo apt-get install python3
       - name: install falsk
         run: pip install Flask
       - name: test app by PyLint
         run: |
           pylint app.py